# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
     num1:
    description: 'Enter number 1'
    default: '4'
    required: true
    type: integer  # Use 'integer' for integer data type
  num2:
    description: 'Enter number 2'
    default: '2'
    required: true
    type: integer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  divide:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
steps:
  # ... other steps (checkout code, install dependencies)

  # Run the divide function and store the result
  - name: Divide numbers
    run: |
      result=$(node path/to/your/script.js divide ${{ inputs.num1 }} ${{ inputs.num2 }})
      echo "The division of ${{ inputs.num1 }} and ${{ inputs.num2 }} is: $result"
